# Generated by Django 5.0.6 on 2024-06-23 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_estadosoli_delete_estadosolicitud'),
    ]

    operations = [
        migrations.RenameField(
            model_name='estadosoli',
            old_name='id_estado',
            new_name='id',
        ),
        migrations.RemoveField(
            model_name='estadosoli',
            name='nombre_estado',
        ),
        migrations.AddField(
            model_name='estadosoli',
            name='estado',
            field=models.CharField(default='Pendiente', max_length=50),
        ),
    ]
