# Generated by Django 5.0.6 on 2024-06-24 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_id_estado_estadosoli_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Solicitudes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
                ('detalle', models.CharField(max_length=50)),
            ],
        ),
    ]
