# Generated by Django 5.0.6 on 2024-06-24 03:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_estadosoli_id_estadosoli_idestado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estadosoli',
            name='idEstado',
            field=models.AutoField(db_column='idEstado', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='solicitudes',
            name='idEstado',
            field=models.ForeignKey(db_column='idEstado', default=1, on_delete=django.db.models.deletion.CASCADE, to='core.estadosoli'),
        ),
    ]
