# Generated by Django 5.0.6 on 2024-06-24 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_estadosoli_idestado'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='solicitudes',
            options={'ordering': ['id']},
        ),
    ]
