# Generated by Django 5.0.6 on 2024-06-24 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_solicitudes_correo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estadosoli',
            name='idEstado',
            field=models.AutoField(db_column='idEstado', primary_key=True, serialize=False),
        ),
    ]
